### ISSUE TITLE
export personalized rss feeds from api

### ISSUE THREAD

**Issue by raifpy** [dailydotdev/daily-api#1121]
Hi all. I want to read daily.dev suggestions in my rss feed reader from mobile. Is it possible to export endpoint with rss support?
```
/rss?cookie=...
maybe
/rss?id=<idFromExtension>&mail=<mailFromExtension>
```

**Comment by idoshamun** [comment]
Hi! This is a dup of https://github.com/dailydotdev/daily/discussions/785.
Let's keep the discussion there
