### ISSUE TITLE
Docs: Improve developer experience when understanding the code base

### ISSUE THREAD

**Issue by Andrei0872** [dailydotdev/daily-api#30]
I think it would be great if there was a section in which we would guide the developer on how to easily understand the code base.

I'm particularly referring to understanding what's going on through using the **debugger** while **running the tests**.
I personally saved a lot of time by following the above approach.

These are the steps that I followed in order to really understand the *magic*  behind this API(I'm assuming you're using VS Code):
1) Open the debugger tab and add a new configuration
2) In your **launch.json**, add the following lines:
```json
"configurations": [
        {
             "type": "node",
             "request": "launch",
             "name": "Mocha Tests",
             "program": "${workspaceRoot}/node_modules/mocha/bin/mocha",
             "args": [
               "--inspect-brk",
               "${workspaceFolder}/test/integration/routes/posts.js"
             ],
             "port": 9229,
             "runtimeVersion": "10.12.0",
             "envFile": "${workspaceFolder}/.env.test",
             "internalConsoleOptions": "neverOpen"
       }
    ]
```
_Note:_ the **.env.test** file is where you put the environment variables so you don't have to issue them manually

3) Add these options in your **.babelrc** file:
```json
"retainLines": true,
 "sourceMaps": "inline"
```
4) Open a test file, place a some breakpoints and start running the tests in debugging mode by pressing **F5** or clicking on the **Start Debugging** button.

**Comment by idoshamun** [comment]
Hi @Andrei0872,
With the release of the new API, I believe this issue is no longer relevant or might need to be updated.
I'm closing this issue, for the time being, feel free to reopen.
