### ISSUE TITLE
Add seed data to docker

### ISSUE THREAD

**Issue by idoshamun** [dailydotdev/daily-api#92]
To complete https://github.com/dailydotdev/daily-apps/issues/110, we must copy seed data to docker so it will be available to `docker-compose` based setup.

**Comment by tevez07b9** [comment]
@idoshamun  On running the seed command on docker gives me a unique constraint error. Maybe there is a duplicate entry.
![image](https://user-images.githubusercontent.com/35212025/161084244-5d4692e3-5f91-4e3a-872c-5d828898bb40.png)

**Comment by rebelchris** [comment]
@tevez07b9 Thanks, we indeed noticed this happening this morning.
Will be working on a fix soon.

For now if you want to make it work you can remove the `IDX_post_canonicalUrl` constraint on the post table and redo the import from scratch.

Will keep you posted once the fix is available.

**Comment by tevez07b9** [comment]
> @tevez07b9 Thanks, we indeed noticed this happening this morning. Will be working on a fix soon.
> 
> For now if you want to make it work you can remove the `IDX_post_canonicalUrl` constraint on the post table and redo the import from scratch.
> 
> Will keep you posted once the fix is available.

Thanks @rebelchris , i am trying to understand the code so that i can contribute to this.
